### ISSUE TITLE
non-trans edges end with a node at different level

### ISSUE THREAD

**Issue by ptpt** [valhalla/meili#27]
During working on #26, it appears that an edge that is neither `trans_up` nor `trans_down` can still end with a node at different level.

Appended following code after [this line](https://github.com/valhalla/meili/blob/9e494889f5d53ad56ebb677bbdb9c855e3dc5f7e/src/meili/candidate_search.cc#L74)

```c++
// L74 if (!edge) continue;

if (opp_edgeid.level() != 2) {
  std::cout << "op edgeid " << edgeid << " " << opp_edgeid << " " << edge->endnode() << " " << edge->trans_up() << edge->trans_down() << std::endl;
}

```

I didn't expect it to print anything because all edges should be at the local level 2, as well as the opposite edges, since all trans edges were filtered out at [here](https://github.com/valhalla/meili/blob/9e494889f5d53ad56ebb677bbdb9c855e3dc5f7e/src/meili/candidate_search.cc#L158), before they were feed into `CandidateQuery::WithinSquaredDistance`.

However I've got tons of output like this:
```c++
op edgeid 2/385026/16162 3/385026/1504 3/385026/160 00
op edgeid 2/385026/16204 3/385026/1505 3/385026/160 00
op edgeid 2/385026/16162 3/385026/1504 3/385026/160 00
op edgeid 2/385026/16204 3/385026/1505 3/385026/160 00
op edgeid 2/385026/16162 3/385026/1504 3/385026/160 00
op edgeid 2/385026/16204 3/385026/1505 3/385026/160 00
op edgeid 2/385026/16162 3/385026/1504 3/385026/160 00
op edgeid 2/385026/16204 3/385026/1505 3/385026/160 00
...
```

We clearly see here that edges that are neither `trans_up` nor `trans_down` (indicated by the trailing double zeros) end with a node at different level, and hence they've got opposite edges at different levels.

@kevinkreiser could you check if this is an issue from the tiled data side, or I made a false assumption here about trans edges here?

The tiled data are `tiles_2016_06_15-01_10_01`.

**Comment by kevinkreiser** [comment]
@ptpt yes we connect level 2 road/bike/ped network to level 3 transit network and back. so you'll also want to exclude those edges. you tell an edge is a transit connect edge using something like: `edge->use() == Use::kTransitConnection`

@gknisely @dnesbitt61 does that look right?

**Comment by dnesbitt61** [comment]
Yes

**Comment by ptpt** [comment]
Thanks for the quick reply.

I will think of this
```c++
assert (edge->trans_up() || edge->trans_down() || edge->use() == Use::kTransitConnection) == (edgeid.level() != edge->endnode().level())
```
is always true, to prevent them from jumping between different levels.

**Comment by kevinkreiser** [comment]
@ptpt please `throw` instead of `assert`
