### ISSUE TITLE
When trying to run the docker image: "Container command 'pbfgraphbuilder' not found or does not exist."

### ISSUE THREAD

**Issue by ezheidtmann** [valhalla/meili#32]
I'm attempting to run Meili in docker by following these instructions:

https://github.com/valhalla/Meili/blob/master/docs/run_service_in_docker.md

The following command fails as shown:

```
$ sudo docker run -it \
    --volume  "${WORK_DIR}":/data \
    --workdir /data \
    valhalla/meili \
    pbfgraphbuilder --conf conf/valhalla.json berlin-latest.osm.pbf
docker: Error response from daemon: Container command 'pbfgraphbuilder' not found or does not exist..
```

**Comment by ezheidtmann** [comment]
Replace `pbfgraphbuilder` with `valhalla_build_tiles` for at least temporary success. Docs need to be updated.

**Comment by ptpt** [comment]
Thanks for the report.
