### ISSUE TITLE
Incorrect matching behavior

### ISSUE THREAD

**Issue by ericrwolfe** [valhalla/meili#38]
Generally followed the instructions in [valhalla/tools](https://github.com/valhalla/tools) with the exact installation steps here [gist](https://gist.github.com/ericrwolfe/ca00eb60b7f8529fd02558b10a6d3aa1).

However, running the `valhalla_map_match_service` and testing an area using the mapillary map matching demo, leads to unexpected results. 

As an example, a trace in Zurich, Switzerland using `?search_radius=40&mode=auto` is matching only to pedestrian paths, and they're disconnected at that:
![incorrect](https://cloud.githubusercontent.com/assets/664805/17987725/7b3e75c0-6ad6-11e6-818a-a2b5fa354319.png)

Running the same trace through the Mapillary hosted service [mm.mapillary.io/mm](http://mm.mapillary.io/mm) matches the points as expected:
![correct](https://cloud.githubusercontent.com/assets/664805/17987727/7edb7480-6ad6-11e6-9143-e32537004c27.png)

I've tested `valhalla_route_service` on the same extract, and the service correctly routes with mode=auto, so it seems the issue might be with this specific installation of meili rather than the valhalla core and tiles:
![valhalla_routing_service](https://cloud.githubusercontent.com/assets/664805/17987713/6be8dc0a-6ad6-11e6-9cb3-bc091a31875a.png)

Any ideas? Has anything significant changed between when you deployed [mm.mapillary.io/mm](http://mm.mapillary.io/mm) and when I pulled down valhalla about 2 weeks ago?

/cc @ptpt

**Comment by ptpt** [comment]
Yes a wrong use of sif's edge filter caused this issue. It should be fixed at this commit https://github.com/valhalla/meili/commit/a87b15cad3820a030ba88cbc985972600fa39ad8. The latest meili should work as expected as mapillary.io/mm does.

**Comment by ericrwolfe** [comment]
Indeed, that was it! Looks like I had pulled the code about 3 days too early.
