### ISSUE TITLE
Published docker image?

### ISSUE THREAD

**Issue by chrisfosterelli** [valhalla/meili#43]
The instructions in the README let people know how to download the git repository and generate an image... which is great, but why not publish an image under `valhalla/meili` on Docker Hub?

Docker hub is a pretty standard place to find that, and meili would fit in fine there under a valhalla organization. Is there a particular reason why users have to download the git repo and build the image locally?

**Comment by ptpt** [comment]
Thanks for the info. Yes, Docker Hub is a better place for this purpose. There is no special reason to build locally if we serve it on Docker Hub. I will forward the issue to https://github.com/valhalla/docker which is working on dockerizing Valhalla packages including meili.

**Comment by chrisfosterelli** [comment]
Cool, thanks! It takes a while to build manually so I'm sure the next few people would appreciate it :)
