### ISSUE TITLE
Wrong candidates

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/meili#58]
Either because the bins are missing stuff or transition logic

**Comment by ptpt** [comment]
We only index local tiles at level 2 for candidate search. Non-local edges are all missing. Does it relate to this issue?

**Comment by kevinkreiser** [comment]
we store all the edges from all of the levels within the level 2 bins. so it should include highways etc. heres a good example of the problem thanks to @smWork @noblige and @yzadik

http://valhalla.github.io/demos/routing/#loc=16,37.503640,-122.244476&locations=[{%22lat%22:37.50127003414561,%22lon%22:-122.24165081975117},{%22lat%22:37.50884073018052,%22lon%22:-122.2533559798103}]&costing=%22auto%22

**Comment by kevinkreiser** [comment]
i strongly suspect that this may be an issue with the bins and im looking into it immediately
