### ISSUE TITLE
Tiles aren't being indexed

### ISSUE THREAD

**Issue by ericrwolfe** [valhalla/meili#60]
Trying to run a vanilla install of meili from the new Valhalla 2.0 release and queries that previously worked with pre-2.0 meili are returning empty results.

Dug into it a bit and it looks like tiles aren't actually being indexed: an EdgeInfo's shape.size() is always 0 here:
https://github.com/valhalla/meili/blob/bbdd2fe2742c15bbd2144b6cb2e0ebde33b3f231/src/meili/candidate_search.cc#L143

/cc @kevinkreiser @kdiluca

**Comment by kevinkreiser** [comment]
i know its a bit of a side step but i wonder if we should go ahead and implement the faster version using the lazy shape decoding while we are in here. its quite a bit faster in loki (>4x) and would certainly be faster here. for reference: https://github.com/valhalla/loki/blob/master/src/loki/search.cc#L246-L265
