### ISSUE TITLE
How to generate specific map into valhalla data

### ISSUE THREAD

**Issue by MirrorrorriN** [valhalla/meili#67]
Hi,in the latest readme,there isn't instruction about how to lead in .osm data.
1.I will get all [NULL NULL ...] in json file even with the test coordinates all in Berlin;
2.I followed the instruction about build osm tiles in history,but failed.
So now with the latest meili, how can I import my osm data to do map matching?Thank you so much

**Comment by ptpt** [comment]
Thanks for report. Check out the latest tutorial https://github.com/valhalla/meili/blob/master/docs/run_service_in_docker.md

Reopen if it still doesn't solve your issue.

**Comment by MirrorrorriN** [comment]
Thank you so much.And I've already figure it out with readme file on Valhalla/Tools.Thank ou for your updating again.
